openapi: "3.0.0"

info:
  "$ref": "./common/info.yaml"

servers:
  - url: http://localhost:4342
    description: Local API Server

  - url: https://placeholder/core
    description: Integration API Server

paths:
  "$ref": "./paths.yaml"

components:
  securitySchemes:
    api_key:
      type: "http"
      scheme: "bearer"
      bearerFormat: JWT

security:
  - api_key: []