export enum ERROR_TYPE {
  BAD_DATA,
  CONFLICT,
  DUPLICATE_RECORD,
  RESOURCE_NOT_FOUND,
  UNABLE_TO_PROCESS,
  UNAUTHORIZED,
}

enum ORG_TYPE {
  CLIENT,
  INTERNAL_DEPARTMENT,
  WAREHOUSE,
}

enum USER_STATUS {
  PENDING_ACTIVATION,
  ACTIVATED,
  DE_ACTIVATED,
  SUSPENDED,
}

export class ApplicationEnums {
  static APP = {
    ERROR_TYPE: ERROR_TYPE,
    ORG_TYPE: ORG_TYPE,
    USER_STATUS: USER_STATUS,
  };
}
